name: Trigger auto deployment for my-container-app

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ main ]
    paths:
    - '**'
    - '.github/workflows/my-container-app-AutoDeployTrigger-09a55bc9-cd2b-4dbf-9b50-67656675a4a7.yml'

  # Allow manual trigger 
  workflow_dispatch:
      
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.MYCONTAINERAPP_AZURE_CREDENTIALS }}
          
      - name: Docker Login
        uses: docker/login-action@v3.0.0
        with:
         Username: jsr2089
         Password: L0ve@dockerhub # recently changed

      - name: Docker Pull Auto Action 
        uses: codebysandip/docker-pull-auto-action@v1.5
        with: 
          docker-image: nginx
          docker-tag: stable-alpine3.17-slim
          domain: docker.io
          hook-secret: v1.0
          
      - name: Deploy to Azure Container Instances
        uses: Azure/aci-deploy@v1
        with: 
          resource-group: aks-rg
          name: my-container-app
          
     

